### ISSUE TITLE
Dev sql dump setup

### ISSUE THREAD

**Issue by hellatan** [DueProcessed/dueprocessed.com#37]

**Comment by hellatan** [comment]
I think this would be good to have sooner than later b/c when you clone this repo, then start everything up, the due processed theme is not set by default and you have to remember to "activate" it in the admin.

**Comment by nameofname** [comment]
I have an opened PR for this : 
https://github.com/DueProcessed/dueprocessed.com/pull/41

Will work with @lilianammmatos to get a better version of the data into the repo from her local (with footnotes, etc.).
